name: ROS melodic CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      - uses: actions/checkout@v1
      - name: Install catkin & package dependencies
        run: |
          cd / && ./ros_entrypoint.sh
          apt-get update
          apt-get install -y python-catkin-tools curl python3-pip

      - name: Setup catkin workspace
        run: |
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make"

      - name: Build package and run unit test
        run: |
          apt-get install -y ros-melodic-code-coverage git
          pip3 install codecov
          pip3 install coverage
          cd ~/catkin_ws/src
          cp -r $GITHUB_WORKSPACE .
          cd ~/catkin_ws
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make run_tests_example_pkg -DENABLE_COVERAGE_TESTING=ON"
          cp ~/.ros/.coverage* ~/catkin_ws
          cd ~/catkin_ws
          # python-coverage combine
          # python-coverage xml
          /bin/bash -c "bash <(curl -s https://codecov.io/bash)"

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ~/catkin_ws