name: ROS melodic CI
on: [push]
jobs:    
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic-ros-base
    steps:
      - uses: actions/checkout@v1
      - name: Install catkin & package dependencies
        run: |
          cd / && ./ros_entrypoint.sh
          apt-get update
          apt-get install -y ros-melodic-catkin python-catkin-tools
          apt-get install -y ros-melodic-rospy-tutorials
          apt-get install -y ros-melodic-roslint

      - name: Setup catkin workspace
        run: |
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make" 
          
      - name: Build package
        run: |
          cd ~/catkin_ws
          cp -r $GITHUB_WORKSPACE .
          /bin/bash -c "source devel/setup.bash && catkin_make"

      - name: Unit tests
        run: |
          sudo apt install -y lcov
          /bin/bash -c "source /opt/ros/melodic/setup.bash"
          cd ~/catkin_ws 
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin config --cmake-args -DCMAKE_CXX_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_C_FLAGS="-Wall -Wno-unused --coverage -fno-inline -fno-inline-small-functions -fno-default-inline" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXE_LINKER_FLAGS="-lgcov""
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make"
          /bin/bash -c "source /opt/ros/melodic/setup.bash && catkin_make run_tests -i && catkin_test_results"